version: 2.1

orbs:
  node: circleci/node@4.0.0

workflows:
  app-tests:
    jobs:
      - test


jobs:
  test:
      docker:
        - image: cimg/node:15.11.0
      steps:
        - checkout
        - run: 
           name: Installing Dependecies
           command: npm install
        - restore_cache:
            keys: 
              - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
        - save_cache:
            paths: 
              - ~/user/local/lib/node_modules
            keys: 
              - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
