version: 2.1

orbs:
  node: circleci/node@4.0.0

workflows:
  app-tests:
    when: 
      and: 
        - equal: [ main, << pipeline.git.branch >> ]
        - << pipeline.parameters.deploy >>
        
    jobs:
      - test

working_directory: /tmp
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts


jobs:
  test:
      docker:
        - image: cimg/node:15.11.0
      steps:
        - checkout
        - run: 
           name: Installing Dependecies
           command: npm install
        - restore_cache:
            keys: 
              - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
        - save_cache:
            paths: 
              - ~/.circleci/config.yml
            keys: 
              - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
